---
# ====== Application: Customers ==============================
id: 7170
identification: 
  name: Customers
  alias: CUSTOMERS
  version: 23.2.0
  application-group: Starter Apps # 170287221760495077

row-search: 
  tokenize: false

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: eba_cust_fw.apex_error_handling

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2
  pass-ecid: N
  copyright-banner: |
    Name: #APP_NAME#
    Copyright (c)2012, #YEAR# Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown 
    at https://oss.oracle.com/licenses/upl/

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Application Express Accounts # 17798789260151217963

authorization: 
  authorization-scheme: APPLICATION SENTRY # 15965136105005268988
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions
  maximum-session-length: 28800
  maximum-session-idle-time: 28800

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Allow from same origin
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: DYMON

globalization: 
  primary-language: English (United States) (en-us)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: false

application-format-masks: 
  date: DS
  timestamp: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APPLICATION_TITLE.'

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:59:&SESSION.'
    page: 59 # Customers

navigation-menu: 
  list-template: Side Navigation Menu # 14857751184094769892
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Application Navigation # 14857842905771835523

navigation-bar: 
  implementation: List
  list: Navigation Bar # 14872150735613499327
  list-template: Navigation Bar # 14857750970564769891

javascript: 
  include-deprecated-or-desupported-javascript-functions: 
  - Pre 18.1
  - 18.x
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#IMAGE_PREFIX#pkgapp_ui/css/5.0#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: true

substitutions: 
- # ====== Substitution: APP_DATE_FORMAT =======================
  id: 7728180845834643
  identification: 
    name: APP_DATE_FORMAT

  value: 
    static-value: DD-MON-YYYY

- # ====== Substitution: GETTING_STARTED_URL ===================
  id: 7728180845834642
  identification: 
    name: GETTING_STARTED_URL

  value: 
    static-value: 'http://www.oracle.com/technetwork/developer-tools/apex/index.html'

- # ====== Substitution: APP_DATETIME_FORMAT ===================
  id: 7728180845834641
  identification: 
    name: APP_DATETIME_FORMAT

  value: 
    static-value: 'DD-MON-YYYY HH24:MI'

- # ====== Substitution: APP_NAME ==============================
  id: 7728180845834640
  identification: 
    name: APP_NAME

  value: 
    static-value: Customers

component-settings: 
- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 1331282187498355
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 99845865119888905
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 120901561877291432
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  settings: 
    attribute-1: N

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 123215027022478467
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 176130148829506820
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 606723357586624531
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 37166093824739

- # ====== Component Setting: NATIVE_IR ========================
  id: 1834292737359673503
  identification: 
    name: NATIVE_IR
    type: Region

  settings: 
    attribute-1: IG

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 1920165900055619340
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 14542516677807628312
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 15189386664489535785
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  settings: 
    attribute-1: N

  subscription: 
    version-number: 37166093824741

